"""Builds quests/registry/quests.json: the quests, side quests, games,
treasures and easter eggs of the bundle, as play.

Most entries are generated by rule from registries the bundle already holds,
so an entry can only point at something that exists:

  side quests   one per hall that has lessons (lessons/registry/lessons.json),
                gated by that hall's own lessons; one per simulator seat
                (sims/registry/sims.json) and one per tool crib, gated by every
                lesson that puts a learner in that seat or at that crib
  games         one per arcade game, gated by the lessons that use the seat the
                game's content is read from (ladder order, at most two)
  page eggs     three per page this pack hooks: a knock on the page's heading,
                a typed word, and a hidden cache (explore-only, band K-5)

The main chain, the module treasures and the quest-page eggs are AUTHORED
below. `unlock_text` is generated from `requires`, never typed. Every id in
`requires` must resolve or the build stops with a named error; there are no
defaults on registry data.

Quests and badges are play: they never enter a completion record and certify
nothing. The registry says so in `honesty`.
"""
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / 'registry' / 'quests.json'

HONESTY = ('Quests, games, treasures, easter eggs and badges are play: they are kept on this '
           'device only, they are never evidence of anything, and they never enter a completion record.')


def need(d, k, where):
    if not isinstance(d, dict):
        raise TypeError(f'{where}: expected an object to read {k!r} from, got {type(d).__name__}')
    if k not in d:
        raise KeyError(f'{where}: required field {k!r} is missing')
    return d[k]


def load(rel):
    return json.loads((ROOT / rel).read_text(encoding='utf-8'))


LESSONS_PATH = 'lessons/registry/lessons.json'
HALLS_PATH = 'pack/registry/halls.json'
SIMS_PATH = 'sims/registry/sims.json'

lessons_reg = load(LESSONS_PATH)
LESSONS = need(lessons_reg, 'lessons', LESSONS_PATH)
LADDER = need(lessons_reg, 'ladder', LESSONS_PATH)
LAYERS = need(LADDER, 'layers', f'{LESSONS_PATH}#ladder')
HALLS = {need(h, 'slug', HALLS_PATH): need(h, 'name', HALLS_PATH) for h in need(load(HALLS_PATH), 'halls', HALLS_PATH)}
SIMS = need(load(SIMS_PATH), 'sims', SIMS_PATH)

LAYER_OF = {lid: int(depth) for depth, ids in LAYERS.items() for lid in ids}
KEY_ORDER = list(LESSONS)


def course_order(ids):
    """The ladder layer, then the registry's key order: how the lessons page orders a course."""
    for i in ids:
        if i not in LAYER_OF:
            raise KeyError(f'{LESSONS_PATH}#ladder.layers holds no layer for lesson {i!r}')
    return sorted(set(ids), key=lambda i: (LAYER_OF[i], KEY_ORDER.index(i)))


def lessons_where(pred):
    return course_order([lid for lid, L in LESSONS.items() if any(pred(s) for s in need(L, 'steps', lid))])


def req(lessons=(), halls=(), quests=()):
    return {'lessons': list(lessons), 'halls': list(halls), 'quests': list(quests)}


Q = []


def add(id, kind, title, world, requires, hint, badge_label, place=None, band=None, trigger=None, target=None,
        riddle=None):
    e = {'id': id, 'kind': kind, 'title': title, 'world': world, 'requires': requires, 'hint': hint,
         'reward': {'badge': 'badge-' + id, 'label': badge_label}, 'provenance': 'AUTHORED'}
    if place is not None:
        e['place'] = place
    if band is not None:
        e['band'] = band
    if trigger is not None:
        e['trigger'] = trigger
    if target is not None:
        e['target'] = target
    if riddle is not None:
        e['riddle'] = riddle
    Q.append(e)


QUEST_PAGE = 'page:web/trade_craft_quests.html'

# ----------------------------------------------------------------- arcade games
# Each game reads its content from one simulator seat's registry entry; it is
# gated by the lessons that put a learner in that seat (ladder order, <= 2).
GAMES = [
    ('game-signal-caller', 'rigging-signals', 'Signal caller',
     'Give the signal the lift card calls, in order, before the clock runs out; finish on STOP.'),
    ('game-load-chart', 'load-chart', 'Chart or refuse',
     'Judge each pick against the chart line at its radius: hook it or refuse it.'),
    ('game-trench-grade', 'excavator-trench', 'Cut to grade',
     'Take each trench cell to its marked depth, stop the flagged cell shallow, dump in the spoil zone.'),
]
for gid, sim, title, hint in GAMES:
    if sim not in SIMS:
        raise KeyError(f'{SIMS_PATH}#sims has no seat {sim!r} for {gid}')
    gate = lessons_where(lambda s, sim=sim: s['kind'] == 'sim' and s['sim'] == sim)
    if not gate:
        raise AssertionError(f'{gid}: no lesson puts a learner in the {sim} seat, so nothing can unlock it')
    add(gid, 'game', title, QUEST_PAGE, req(gate[:2]), hint, title + ' player', place=sim)

# The crib game reads the tool crib that the most lessons send a learner to.
CRIBS_PATH = 'tools/registry/toolcribs.json'
CRIBS = need(load(CRIBS_PATH), 'cribs', CRIBS_PATH)
_crib_use = {}
for _lid, _L in LESSONS.items():
    for _s in _L['steps']:
        if _s['kind'] == 'crib':
            _crib_use.setdefault(_s['crib'], set()).add(_lid)
if not _crib_use:
    raise AssertionError('no lesson has a crib step, so the crib game has nothing to gate on')
CRIB_GAME = sorted(_crib_use, key=lambda c: (-len(_crib_use[c]), c))[0]
if CRIB_GAME not in CRIBS:
    raise KeyError(f'{CRIBS_PATH}#cribs has no crib {CRIB_GAME!r}, which lessons send learners to')
_gate = course_order(_crib_use[CRIB_GAME])
add('game-crib-match', 'game', 'Crib match', QUEST_PAGE, req(_gate[:2]),
    'Read what a tool is for and pick it off the crib wall.', 'Crib match player', place=CRIB_GAME)

# ----------------------------------------------------------------- main chain
add('main-report-in', 'main', 'Report in at the quest board', QUEST_PAGE, req(),
    'Open the quest board and press "Report in".', 'Reported in', place='quest-board', band='K-5')
add('main-first-card', 'main', 'Call the first card', QUEST_PAGE,
    req(['riggers-first-card'], quests=['main-report-in']),
    'Walk the riggers\' first lesson, then come back to the board.', 'First card called')
add('main-call-the-lift', 'main', 'Call the lift', QUEST_PAGE,
    req(quests=['main-first-card', 'game-signal-caller']),
    'Win a round of Signal caller in the arcade.', 'Lift called')
add('main-read-the-chart', 'main', 'Read the chart before the pick', QUEST_PAGE,
    req(quests=['main-call-the-lift', 'game-load-chart']),
    'Win a round of Chart or refuse in the arcade.', 'Chart read')
add('main-dig-safe', 'main', 'Dig to grade, miss the utility', QUEST_PAGE,
    req(quests=['main-read-the-chart', 'game-trench-grade']),
    'Win a round of Cut to grade in the arcade.', 'Dug to grade')
add('main-crew-chief', 'main', 'Crew of three trades', QUEST_PAGE,
    req(halls=['riggers', 'crane-ops', 'operating-eng'], quests=['main-dig-safe']),
    'Finish a lesson in the riggers\', crane operators\' and operating engineers\' halls.', 'Crew of three')

# ----------------------------------------------------------------- side quests
# One per hall that has lessons, gated by that hall's own lessons.
by_hall = {}
for lid, L in LESSONS.items():
    by_hall.setdefault(need(L, 'hall', lid), []).append(lid)
for hall in sorted(by_hall):
    if hall not in HALLS:
        raise KeyError(f'{HALLS_PATH} has no hall {hall!r}, which lessons use')
    ids = course_order(by_hall[hall])
    first = LESSONS[ids[0]]
    add(f'side-hall-{hall}', 'side', f'Report to {HALLS[hall]}', f'hall:{hall}',
        req(ids, [hall]), f'Walk to the {need(first, "room_label", ids[0])} and report in once the hall\'s lessons are walked.',
        f'{HALLS[hall]} regular', place=need(first, 'room_label', ids[0]))

# One per simulator seat and one per tool crib, gated by every lesson using it.
for sim in sorted(SIMS):
    ids = lessons_where(lambda s, sim=sim: s['kind'] == 'sim' and s['sim'] == sim)
    if not ids:
        continue
    name = need(SIMS[sim], 'name', f'{SIMS_PATH}#sims.{sim}')
    add(f'side-seat-{sim}', 'side', f'Crew the {name} seat', 'campus',
        req(ids), f'Every lesson that puts you in the {name} seat, walked.', f'{name} crew', place=sim)
cribs = sorted({s['crib'] for L in LESSONS.values() for s in L['steps'] if s['kind'] == 'crib'})
for crib in cribs:
    ids = lessons_where(lambda s, crib=crib: s['kind'] == 'crib' and s['crib'] == crib)
    add(f'side-crib-{crib}', 'side', f'Sign out the {crib} crib', 'campus',
        req(ids), f'Every lesson that sends you to the {crib} tool crib, walked.', f'{crib} crib regular', place=crib)

# The wilds (wilds/registry/wilds.json, published by WILDS): one side quest per
# site, gated by the lessons the site itself names; one explore-only treasure
# per world at its trailhead. Read only when the registry exists.
WILDS_PATH = 'wilds/registry/wilds.json'
if (ROOT / WILDS_PATH).exists():
    for world in need(load(WILDS_PATH), 'worlds', WILDS_PATH):
        wid = need(world, 'id', WILDS_PATH)
        wname = need(world, 'name', f'{WILDS_PATH}#{wid}')
        add(f'treasure-wilds-{wid}-trailhead', 'treasure', f'Sign the trailhead book: {wname}', f'wilds:{wid}', req(),
            f'Every trail in {wname} starts at the trailhead. Find its book.', f'{wname} walker',
            place='trailhead', band='K-5')
        for site in need(world, 'sites', f'{WILDS_PATH}#{wid}'):
            sid = need(site, 'id', f'{WILDS_PATH}#{wid}.sites')
            named = [need(l, 'id', f'{WILDS_PATH}#{sid}.lessons') for l in need(site, 'lessons', f'{WILDS_PATH}#{sid}')]
            missing = [l for l in named if l not in LESSONS]
            if missing:
                raise KeyError(f'{WILDS_PATH}#{sid} names lessons {missing} that {LESSONS_PATH} does not hold')
            if named:
                gate = req(course_order(named))
            else:
                # no lessons of its own: gated by the halls the site names, and
                # only when every one of them has a lesson that could satisfy it
                halls = [need(h, 'id', f'{WILDS_PATH}#{sid}.halls') for h in need(site, 'halls', f'{WILDS_PATH}#{sid}')]
                if not halls or any(h not in HALLS or h not in by_hall for h in halls):
                    continue
                gate = req(halls=halls)
            add(f'side-wilds-{sid}', 'side', need(site, 'title', f'{WILDS_PATH}#{sid}'), f'wilds:{wid}',
                gate, need(site, 'work', f'{WILDS_PATH}#{sid}'),
                need(site, 'title', f'{WILDS_PATH}#{sid}') + ' crew', place=sid)
        # one explore-only treasure per hidden cache; its riddle is WILDS's own
        for c in need(world, 'caches', f'{WILDS_PATH}#{wid}'):
            cid = need(c, 'id', f'{WILDS_PATH}#{wid}.caches')
            kind = need(c, 'kind', f'{WILDS_PATH}#{cid}')
            riddle = need(c, 'riddle', f'{WILDS_PATH}#{cid}')
            label = {'cache': 'Cache', 'hollow': 'Hollow', 'summit': 'Summit register'}
            if kind not in label:
                raise KeyError(f'{WILDS_PATH}#{cid}: cache kind {kind!r} is not one of {sorted(label)}')
            add(f'treasure-wilds-{cid}', 'treasure', f'{label[kind]} in {wname}', f'wilds:{wid}', req(),
                riddle, f'{label[kind]} finder: {wname}', place=cid, band='K-5', riddle=riddle)

# The campus and its halls (CAMPUS publishes these entries; the 3D page binds
# them itself and calls TCQuests.find(id), so they carry no trigger fields).
CAMPUS_SRC = 'quests/source/campus.json'
_campus = need(load(CAMPUS_SRC), 'entries', CAMPUS_SRC)
for e in _campus:
    eid = need(e, 'id', CAMPUS_SRC)
    for k in ('kind', 'title', 'world', 'place', 'requires', 'hint', 'reward', 'provenance'):
        need(e, k, f'{CAMPUS_SRC}#{eid}')
    if e['kind'] not in ('treasure', 'egg'):
        raise ValueError(f'{CAMPUS_SRC}#{eid}: kind {e["kind"]!r} - CAMPUS entries are treasure|egg')
    if not (e['world'] == 'campus' or e['world'].startswith('hall:')):
        raise ValueError(f'{CAMPUS_SRC}#{eid}: world {e["world"]!r} is not campus | hall:<id>')
    if 'trigger' in e or 'target' in e:
        raise ValueError(f'{CAMPUS_SRC}#{eid}: campus entries carry no trigger fields (the 3D page binds them)')
    if e['provenance'] != 'AUTHORED':
        raise ValueError(f'{CAMPUS_SRC}#{eid}: provenance must be AUTHORED')
    r = e['requires']
    add(eid, e['kind'], e['title'], e['world'],
        req(need(r, 'lessons', eid), need(r, 'halls', eid), need(r, 'quests', eid)), e['hint'],
        need(e['reward'], 'label', f'{CAMPUS_SRC}#{eid}.reward'), place=e['place'],
        band=e['band'] if 'band' in e else None)
    if Q[-1]['reward']['badge'] != need(e['reward'], 'badge', f'{CAMPUS_SRC}#{eid}.reward'):
        raise ValueError(f'{CAMPUS_SRC}#{eid}: reward badge must be badge-{eid}')

# Modules no page reads today, brought into play on the quest board.
add('side-inspect-sequencer-eval', 'side', 'Inspect the sequencer eval', QUEST_PAGE, req(),
    'Open the eval drawer on the quest board and read what the simulation does not prove.',
    'Eval inspector', place='eval-drawer', band='9-10')
add('treasure-compliance-placard', 'treasure', 'Read the compliance placard', QUEST_PAGE, req(),
    'A placard hangs by the badge shelf. Read it.', 'Placard reader', place='compliance-placard', band='6-8',
    riddle='Before the lift, the wall speaks: what the bundle asks, and what a record can show.')
add('treasure-venue-room', 'treasure', 'The measured room', QUEST_PAGE, req(),
    'Somewhere on the board is a room that was measured, not drawn.', 'Room measurer',
    place='venue-clue', band='6-8', riddle='Floors counted from a scan, clear heights from triangles: find the room.')
add('treasure-sbom-manifest', 'treasure', 'The parts manifest', QUEST_PAGE, req(),
    'Every piece this bundle ships is on a list. Find the list.', 'Manifest reader',
    place='sbom-manifest', band='11-12', riddle='Count the parts before you trust the machine.')

# ----------------------------------------------------------------- parishes
# The walkable parish world (layers/registry/layers.json, this pack's sibling;
# its parishes come from parishes/ or, until that lands, its Orleans stub).
# Every entry is play and explore-only; the parish page calls TCQuests.find(id)
# for treasures (a station opened, a parish entered, a border crossed, a first
# ride of a medium, a first talk with a guide) and the log completes quests
# whose requires are met. Stations and paths are never gated.
LAYERS_PATH = 'layers/registry/layers.json'
_layers = load(LAYERS_PATH)
PARISHES = need(_layers, 'parishes', LAYERS_PATH)
LAYER_LABEL = {k: need(v, 'label', f'{LAYERS_PATH}#layers.{k}') for k, v in need(_layers, 'layers', LAYERS_PATH).items()}
# AUTHORED typed words for each parish's egg, dealt in FIPS order (plain delta words, no place facts)
PARISH_WORDS = ['levee', 'bayou', 'ferry', 'marsh', 'delta', 'batture', 'cypress', 'pirogue', 'spillway',
                'crawfish', 'heron', 'lagoon', 'egret', 'barge', 'oyster', 'tugboat']
# the travel media the fleet offers (FLEET: land vehicles + watercraft); checked against fleet/ when it exists
MEDIA = ('land', 'water')
FLEET_PATH = 'fleet/registry/fleet.json'
if (ROOT / FLEET_PATH).exists():
    _fleet = load(FLEET_PATH)
    _fleet_media = sorted({need(v, 'medium', f'{FLEET_PATH}#fleet[]') for v in need(_fleet, 'fleet', FLEET_PATH)})
    if _fleet_media != sorted(MEDIA):
        raise ValueError(f'{FLEET_PATH} media {_fleet_media} are not exactly {sorted(MEDIA)}')
if len(PARISHES) > len(PARISH_WORDS):
    raise AssertionError(f'{len(PARISHES)} parishes but only {len(PARISH_WORDS)} AUTHORED egg words; add words')
_fips_all = [need(p, 'fips', LAYERS_PATH) for p in PARISHES]
_edges = set()
for pi, p in enumerate(PARISHES):
    fips = p['fips']
    pname = need(p, 'name', f'{LAYERS_PATH}#{fips}')
    pw = f'parish:{fips}'
    add(f'treasure-parish-{fips}-arrive', 'treasure', f'Set foot in {pname}', pw, req(),
        f'Walk, drive or sail into {pname}.', f'{pname} explorer', place='arrive', band='K-5')
    for lm in need(p, 'landmarks', f'{LAYERS_PATH}#{fips}'):
        lid = need(lm, 'id', f'{LAYERS_PATH}#{fips}.landmarks')
        lname = need(lm, 'name', f'{LAYERS_PATH}#{fips}.landmarks.{lid}')
        add(f'treasure-parish-{fips}-lm-{lid}', 'treasure', f'Reach {lname}', pw, req(),
            f'Find {lname} in {pname}.', f'{lname} visitor', place=lid, band='K-5')
    add(f'egg-parish-{fips}-word', 'egg', 'The parish word', pw, req(),
        'Type a word the delta is made of.', f'Word finder: {pname}', trigger=f'typed:{PARISH_WORDS[pi]}', band='K-5')
    add(f'treasure-guide-{fips}', 'treasure', f'Talk to a guide in {pname}', pw, req(),
        f'A guide in {pname} quotes the registries word for word. Say hello.', f'Guide listener: {pname}',
        place='guide', band='K-5')
    for st in need(p, 'stations', f'{LAYERS_PATH}#{fips}'):
        sid = need(st, 'id', f'{LAYERS_PATH}#{fips}.stations')
        if need(st, 'treasure', sid) != f'treasure-station-{sid}':
            raise ValueError(f'{LAYERS_PATH}#{sid}: treasure must be treasure-station-{sid}')
        lab = LAYER_LABEL[need(st, 'layer', sid)]
        add(f'treasure-station-{sid}', 'treasure', f'{lab}: {need(st, "title", sid)}', pw, req(),
            f'Stand at the {lab} station in {pname} and open it.', f'Station visitor: {need(st, "title", sid)}',
            place=sid)
    for path in need(p, 'paths', f'{LAYERS_PATH}#{fips}'):
        pid = need(path, 'id', f'{LAYERS_PATH}#{fips}.paths')
        if need(path, 'gated', f'{LAYERS_PATH}#{fips}.paths.{pid}') is not False:
            raise ValueError(f'{LAYERS_PATH}#{fips}.paths.{pid}: a path is a suggestion, never gated')
        steps = need(path, 'steps', f'{LAYERS_PATH}#{fips}.paths.{pid}')
        step_q = [s if pid == 'explorer' else f'treasure-station-{s}' for s in steps]
        add(f'side-parish-{fips}-{pid}', 'side', f'{need(path, "label", pid)} in {pname}', pw, req(quests=step_q),
            f'Every stop on the {need(path, "label", pid)} in {pname}, in any order.',
            f'{need(path, "label", pid)}: {pname}', place=f'path-{pid}')
    for other in need(p, 'adjacent', f'{LAYERS_PATH}#{fips}'):
        if other in _fips_all:
            _edges.add(tuple(sorted((fips, other))))
for a, b in sorted(_edges):
    na = next(p['name'] for p in PARISHES if p['fips'] == a)
    nb = next(p['name'] for p in PARISHES if p['fips'] == b)
    add(f'treasure-border-{a}-{b}', 'treasure', f'Cross from {na} to {nb}', 'parishes', req(),
        f'The border between {na} and {nb} is shared. Cross it, either way.', f'Border crosser: {na} / {nb}',
        place=f'border-{a}-{b}', band='K-5')
for med in MEDIA:
    add(f'treasure-ride-{med}', 'treasure', {'land': 'Drive a land vehicle', 'water': 'Take a boat out'}[med],
        'parishes', req(), {'land': 'Climb into any land vehicle and drive it.',
                            'water': 'Board any watercraft and take it onto the water.'}[med],
        {'land': 'Land driver', 'water': 'Water pilot'}[med], place=f'ride-{med}', band='K-5')
add('main-parishes-media', 'main', 'Ride one of each medium', 'parishes',
    req(quests=[f'treasure-ride-{m}' for m in MEDIA]), 'Drive on land and take a boat on the water.',
    'Every medium')
add('main-parishes-regions', 'main', f'Set foot in all {len(PARISHES)} parishes', 'parishes',
    req(quests=[f'treasure-parish-{f}-arrive' for f in _fips_all]), 'Enter every parish of the world.',
    'Every parish')
add('main-parishes-guides', 'main', f'Talk to {len(PARISHES)} guides', 'parishes',
    req(quests=[f'treasure-guide-{f}' for f in _fips_all]), 'Talk to a guide in every parish.', 'Guide listener')
if _edges:
    add('main-parishes-borders', 'main', 'Cross every connected border', 'parishes',
        req(quests=[f'treasure-border-{a}-{b}' for a, b in sorted(_edges)]),
        f'Cross each of the {len(_edges)} shared borders at least once.', 'Border walker')

# ----------------------------------------------------------------- quest page eggs
add('egg-quests-konami', 'egg', 'The old code', QUEST_PAGE, req(), 'Some keys remember an older arcade.',
    'Old-code keeper', trigger='konami', band='K-5', riddle='Up, up, down, down, left, right, left, right, B, A.')
add('egg-quests-hardhat', 'egg', 'Hard hat on', QUEST_PAGE, req(), 'Type what goes on before anything else.',
    'Hard hat', trigger='typed:hardhat', band='K-5', riddle='It goes on first and comes off last. Type it.')

# ----------------------------------------------------------------- page eggs
# (page, slug, the typed word, the hint for the word). Every page here gets a
# knock on its <h1>, a typed word and a hidden cache.
PAGE_EGGS = [
    ('index.html', 'home', 'union', 'Type the word the halls stand together in.'),
    ('web/trade_craft_map.html', 'map', 'compass', 'Type what points north.'),
    ('web/trade_craft_interactive.html', 'interactive', 'district', 'Type what eight halls share.'),
    ('web/trade_craft_geomap.html', 'geomap', 'survey', 'Type what a surveyor does, in the find box or anywhere.'),
    ('web/trade_craft_spaces.html', 'spaces', 'blueprint', 'Type the plan before the build.'),
    ('web/trade_craft_worksites.html', 'worksites', 'toolbox', 'Type the talk before the shift.'),
    ('web/trade_craft_contribute.html', 'contribute', 'apprentice', 'Type who learns beside a journeyworker.'),
    ('web/trade_craft_dashboard.html', 'dashboard', 'gauge', 'Type what a dial reads from.'),
    ('web/trade_craft_fabric.html', 'fabric', 'weave', 'Type what threads do.'),
    ('web/trade_craft_ladder.html', 'ladder', 'rung', 'Type what you climb one at a time.'),
    ('web/trade_craft_languages.html', 'languages', 'hello', 'Type a greeting.'),
    ('web/smartcitix_trade_craft_academy.html', 'spec', 'plumb', 'Type what a true wall is.'),
    ('web/trade_craft_quests.html', 'quests', 'arcade', 'Type where the games are.'),
    ('console/trade_craft_console.html', 'console', 'mentor', 'Type who voices the system.'),
]
for page, slug, word, whint in PAGE_EGGS:
    w = f'page:{page}'
    if not (ROOT / page).exists() and page != 'web/trade_craft_quests.html':
        raise FileNotFoundError(f'page eggs name {page}, which does not exist')
    add(f'egg-{slug}-knock', 'egg', 'Knock three times', w, req(), 'Knock on the page\'s heading three times.',
        'Knocker: ' + slug, trigger='clicks:3', target='h1', band='K-5')
    add(f'egg-{slug}-word', 'egg', 'The word', w, req(), whint, 'Word finder: ' + slug,
        trigger=f'typed:{word}', band='K-5')
    add(f'treasure-{slug}-cache', 'treasure', 'A hidden cache', w, req(),
        'A small mark sits at the foot of the page. Look closely.', 'Cache finder: ' + slug, band='K-5')
add('egg-home-konami', 'egg', 'The old code at the front door', 'page:index.html', req(),
    'Some keys remember an older arcade.', 'Front-door code', trigger='konami', band='K-5',
    riddle='Up, up, down, down, left, right, left, right, B, A.')

# Treasure hunt that crosses pages: gated by every page cache.
caches = [f'treasure-{slug}-cache' for _, slug, _, _ in PAGE_EGGS]
add('main-cartographer', 'main', 'Every cache on the map', QUEST_PAGE, req(quests=caches),
    'Find the hidden cache at the foot of every page.', 'Cartographer', band='K-5')

# ----------------------------------------------------------------- resolve + unlock text
ids = [q['id'] for q in Q]
dupes = sorted({i for i in ids if ids.count(i) > 1})
if dupes:
    raise AssertionError(f'quest ids declared twice: {dupes}')
by_id = {q['id']: q for q in Q}
KINDS = ('main', 'side', 'game', 'treasure', 'egg')
BANDS = ('K-5', '6-8', '9-10', '11-12')
for q in Q:
    if q['kind'] not in KINDS:
        raise ValueError(f'{q["id"]}: kind {q["kind"]!r} is not one of {KINDS}')
    if 'band' in q and q['band'] not in BANDS:
        raise ValueError(f'{q["id"]}: band {q["band"]!r} is not one of {BANDS}')
    w = q['world']
    if not (w == 'campus' or w.startswith('hall:') or w.startswith('wilds:') or w.startswith('page:')
            or w == 'parishes' or w.startswith('parish:')):
        raise ValueError(f'{q["id"]}: world {w!r} is not campus | hall:<id> | wilds:<id> | page:<path> | parishes | parish:<fips>')
    if w.startswith('parish:') and w[7:] not in _fips_all:
        raise KeyError(f'{q["id"]}: world names parish {w[7:]!r}, which {LAYERS_PATH} does not hold')
    if w.startswith('hall:') and w[5:] not in HALLS:
        raise KeyError(f'{q["id"]}: world names hall {w[5:]!r}, which {HALLS_PATH} does not hold')
    r = q['requires']
    for lid in r['lessons']:
        if lid not in LESSONS:
            raise KeyError(f'{q["id"]}: requires lesson {lid!r}, which {LESSONS_PATH} does not hold')
    for h in r['halls']:
        if h not in HALLS:
            raise KeyError(f'{q["id"]}: requires hall {h!r}, which {HALLS_PATH} does not hold')
        if h not in by_hall:
            raise KeyError(f'{q["id"]}: requires hall {h!r}, which has no lesson that could satisfy it')
    for qid in r['quests']:
        if qid not in by_id:
            raise KeyError(f'{q["id"]}: requires quest {qid!r}, which is not in this registry')
    if 'band' in q and q['band'] == 'K-5':
        if r['lessons'] or r['halls']:
            raise AssertionError(f'{q["id"]}: a K-5 entry must be explore-only (no lessons, no seats)')


def unlock_text(r):
    parts = []
    if r['lessons']:
        parts.append('walk ' + ', '.join(f'"{LESSONS[i]["title"]}"' for i in r['lessons']))
    if r['halls']:
        parts.append('finish a lesson in ' + ', '.join(HALLS[h] for h in r['halls']))
    if r['quests']:
        parts.append('finish ' + ', '.join(f'"{by_id[i]["title"]}"' for i in r['quests']))
    return ('Open to everyone.' if not parts else 'To unlock: ' + '; '.join(parts) + '.')


for q in Q:
    q['unlock_text'] = unlock_text(q['requires'])

# cycle check over requires.quests
state = {}


def visit(i, path):
    if state.get(i) == 1:
        raise AssertionError('quest requirements form a cycle: ' + ' -> '.join(path + [i]))
    if state.get(i) == 2:
        return
    state[i] = 1
    for j in by_id[i]['requires']['quests']:
        visit(j, path + [i])
    state[i] = 2


for i in by_id:
    visit(i, [])

counts = {k: sum(1 for q in Q if q['kind'] == k) for k in KINDS}
stamp = hashlib.sha256(pathlib.Path(__file__).read_bytes()
                       + (ROOT / LESSONS_PATH).read_bytes() + (ROOT / SIMS_PATH).read_bytes()
                       + (ROOT / CAMPUS_SRC).read_bytes() + (ROOT / LAYERS_PATH).read_bytes()
                       + ((ROOT / FLEET_PATH).read_bytes() if (ROOT / FLEET_PATH).exists() else b'')
                       + ((ROOT / WILDS_PATH).read_bytes() if (ROOT / WILDS_PATH).exists() else b'')).hexdigest()[:16]
doc = {
    'pack': 'quests',
    'product': need(lessons_reg, 'product', LESSONS_PATH),
    'pack_version': need(lessons_reg, 'pack_version', LESSONS_PATH),
    'source_stamp': stamp,
    'reads': [LESSONS_PATH, HALLS_PATH, SIMS_PATH, CRIBS_PATH, WILDS_PATH, CAMPUS_SRC, LAYERS_PATH, FLEET_PATH],
    'parishes': _fips_all,
    'honesty': HONESTY,
    'counts': counts,
    'halls_with_side_quests': sorted(by_hall),
    'quests': Q,
}
text = json.dumps(doc, indent=1, ensure_ascii=False) + '\n'
if '--check' in sys.argv:
    if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
        sys.exit(f'{OUT.relative_to(ROOT)} is stale: run python3 quests/build.py')
    print(f'{OUT.relative_to(ROOT)} is current')
else:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}: {len(Q)} entries {counts}')
