#!/usr/bin/env python3
"""The wiki: a page per map, a page per district, generated from the packs.

Every figure, roster entry and district grouping on these pages is read from
the verified registries — the union registry, the module manifest, the hall
files and the skill graph — so the wiki cannot disagree with the pack. The
content graphs are Mermaid, which GitHub renders natively.

    python3 wiki/build_wiki.py           # regenerate every page
    python3 wiki/build_wiki.py --check   # fail if any page is stale

The --check mode exists for the same reason the console has a staleness
guard: a generated page that nobody regenerates is a page that lies.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent


def _pack_root():
    for cand in (HERE, *HERE.parents):
        if (cand / 'pack').is_dir() and (cand / 'unions').is_dir():
            return cand
    raise RuntimeError('cannot locate the packs from ' + str(HERE))


ROOT = _pack_root()
sys.path.insert(0, str(ROOT / 'web'))
from interiors import ROOMS  # noqa: E402

manifest = json.load(open(ROOT / 'pack/manifest.json'))
L = manifest['ledger']
halls = json.load(open(ROOT / 'pack/registry/halls.json'))['halls']
unions = json.load(open(ROOT / 'unions/registry/unions.json'))
districts = json.load(open(ROOT / 'unions/registry/districts.json'))['districts']
campuses = json.load(open(ROOT / 'unions/registry/campuses.json'))['campuses']
geo = json.load(open(ROOT / 'geo/registry/campuses_geo.json'))
finishes = json.load(open(ROOT / 'surfaces/registry/finishes.json'))
sims = json.load(open(ROOT / 'sims/registry/sims.json'))
schools = json.load(open(ROOT / 'schools/registry/schools.json'))
chapters = json.load(open(ROOT / 'unions/registry/chapters.json'))
tools = json.load(open(ROOT / 'tools/registry/toolcribs.json'))
skills = json.load(open(ROOT / 'pack/registry/skills.json'))['skills']
by_slug = {h['slug']: h for h in halls}

LOCALES = {f.stem: json.load(open(f))
           for f in sorted((ROOT / 'i18n/locales').glob('*.json'))}

F = lambda x: f"{x:,}"
FOOTER = ('\n---\n\n*Generated by `wiki/build_wiki.py` from the verified '
          'registries — edit the sources, not this page. '
          f'Adaptive Stack v3.2 · pack {manifest["pack_version"]}.*\n')


def level_states(slug):
    doc = json.load(open(ROOT / f'pack/registry/halls/{slug}.json'))
    c = {'live': 0, 'calibrating': 0, 'schema_ok': 0, 'draft': 0}
    for lv in doc['levels']:
        c[lv['state']] += 1
    return c


def mermaid_id(slug):
    return slug.replace('-', '_')


# ------------------------------------------------------------------ Home ---
def page_home():
    n_anchors = sum(len(v) for v in geo['anchors'].values())
    route_rows = '\n'.join(
        f'| {campuses[r["from"]]["city"]} ↔ {campuses[r["to"]]["city"]} '
        f'| {r["km"]:,} km |'
        for r in geo['routes_km'])
    campus_rows = '\n'.join(
        f'| **{c["name"]}** | {c["city"]}, {c["region"]} | {c["tagline"]} '
        f'| {", ".join(districts[d]["name"] for d in c["districts"])} '
        f'| {len(c["halls"])} |'
        for c in campuses.values())
    dist_rows = '\n'.join(
        f'| [{d["name"]}](District-{k}.md) | {d["tagline"]} | {len(d["halls"])} |'
        for k, d in districts.items())
    langs = ' · '.join(c['language'] for c in LOCALES.values())
    graph_edges = '\n'.join(
        f'  campus --> {mermaid_id(k)}["{d["name"]}<br/>{len(d["halls"])} halls"]'
        f'\n  click {mermaid_id(k)} "District-{k}.md"'
        for k, d in districts.items())
    return f'''# SmartCiti.X : Trade Craft Academy — wiki

*powered by AGI Corp*

Gamified training to enhance robotic and human integrations: a network of
**{L["halls"]} union training halls** in **{len(districts)} districts** on one
campus, addressing **{F(L["total_modules"])} modules** generated from
{F(manifest["authored_objects"])} authored skeleton objects.

## The maps

Every map is generated from the registries, and each has a page here with its
content graph and details:

| Map | What it shows | Page |
|---|---|---|
| **Interactive map** (`web/trade_craft_interactive.html`) | All {L["halls"]} halls with toggleable layers — districts, pipeline, module layers, training stations — hall floor plans and quizzes, in every locale, searchable and deep-linkable | [Campus-Map](Campus-Map.md) |
| **3D environment** (`web/trade_craft_3d.html`) | The whole network in 3D — three city campuses on one board, each campus a ringed district city of buildings, each building an enterable hall with rooms, fixtures, station beacons and first-person walk mode | [Campus-Map](Campus-Map.md) |
| Campus map (`web/trade_craft_map.html`) | All {L["halls"]} halls in {len(districts)} districts, with pipeline state | [Campus-Map](Campus-Map.md) |
| Hall floor plans (inside the campus map) | A generated interior for every hall — {L["halls"]} plans, 11 rooms each | [Interiors-Map](Interiors-Map.md) |
| Skill graph (`pack/registry/skills.json`) | {F(len(skills))} skills and the edges that sequence practice | [Skill-Graph](Skill-Graph.md) |
| Languages (`web/trade_craft_languages.html`) | The Academy overview in {len(LOCALES)} languages | [Languages](Languages.md) |
| **Simulators** (inside the 3D environment) | {len(sims["sims"])} operable seats — schematic physics, deterministic rubrics, pre-shift walkarounds, bound to real skills in {len(sims["hall_bindings"])} halls | [Simulators](Simulators.md) |
| **Toolrooms** (inside the 3D + interactive maps) | {len(tools["cribs"])} district tool cribs — {sum(len(c["tools"]) for c in tools["cribs"].values())} tools with the deterministic crib drill | [Toolrooms](Toolrooms.md) |
| **Network geomap** (`web/trade_craft_geomap.html`) | The geo registry on a real WGS84 map (MapLibre, no basemap tiles): campuses, {n_anchors} RECORDED anchors, great-circle routes, RECORDED city frames | [Campus-Map](Campus-Map.md) |

## The campus at a glance

```mermaid
flowchart LR
  campus(("Treasure Island<br/>campus"))
{graph_edges}
```

## The campuses

The network trains in three planned locations — named for real cities, with
no site surveyed and no address recorded:

| Campus | Where | Trains | Districts | Halls |
|---|---|---|---|---|
{campus_rows}

### Real geography

The geo registry anchors each campus to a real WGS84 coordinate — Oakland's
is RECORDED verbatim from the Locator.X city table (Apache-2.0), the others
are DERIVED place centroids, and every distance below is recomputed from
the coordinates by the suite rather than trusted. A coordinate anchors a
map; it does not claim a parcel.

| Route | Great-circle distance |
|---|---|
{route_rows}

The registry also ships `geo/registry/campuses.geojson` — standard GeoJSON,
directly consumable by any Mapbox/MapLibre-compatible stack. The 3D network
view places its campus plates by these true bearings, with the real
kilometres on the route labels.

Around each campus sit **{n_anchors} RECORDED anchors** — real cities and
institutions copied verbatim from Locator.X's committed tables (the Bay
Area city table and the New Orleans POI table, Apache-2.0) and
cross-checked against those files at build time. The network view marks
each at its true bearing on the campus plate rim, real kilometres on the
label.

Every campus now carries a **RECORDED city frame** — the centre and view
bounds of Locator.X's own maps (the NOLA region record for New Orleans;
the Bay Area map's committed frame, shared by both Bay campuses),
cross-checked the same way — which is what lets each campus grow a
**walkable city layer** in 3D. New Orleans lays its seven institutions
at true east/north offsets (13 units per real kilometre) joined to the
ring road by avenues; Treasure Island sits as an **island in the Bay**,
its eight RECORDED cities reached by schematic ferry lines and the two
Bay Bridge spans at true bearings with distance log-eased the way the
network view does it (real kilometres stay on every label); Oakland
keeps its waterfront. The avenues, ferries, bridges and water are
SCHEMATIC, and the in-page labels say which is which — places RECORDED,
everything drawn between them schematic.

### The regional chapter network

Every hall keeps its **home campus** — where its district trains — and
holds a **regional chapter** at each of the other two, so all 111 trades
train in all three regions: **{chapters["count"]} chapter seats** in
total, and each campus plaza carries a Regional Chapter Hall listing the
{"/".join(str(v) for v in chapters["hosted"].values())} unions it hosts
from elsewhere. This is the Academy's own regional structure across its
planned campuses, not a claim about any real union's locals or
jurisdictions — no local is named.

### The New Orleans Trades Edition

The Crescent Works campus and its city layer also ship as their own
artifact — the **SmartCiti.X New Orleans Trades Edition**, booting
straight into the walkable New Orleans map. On the Cognition.X platform
(this foundation's block-based curriculum system), the edition is
supplemented by the **SmartCiti.X : New Orleans Trades** community pack
alongside the Louisiana OS edition: five tracks — the port and its
cranes, safe ground below sea level, drainage and the storm, restoration
after the wind, and the craft pathway itself — authored from this
repository's registries (the simulators' control discipline, the surface
and conditions doctrine, the RECORDED geography), with transfer checks
phrased against the learner's own parish.

## The districts

| District | Tagline | Halls |
|---|---|---|
{dist_rows}

## Languages

{langs} — see [Languages](Languages.md).

## Elsewhere in this repository

- [`ROADMAP.md`](../ROADMAP.md) — the phased plan from v3.2 forward
- [`SmartCitiX_TradeCraft_Academy_Spec.md`](../SmartCitiX_TradeCraft_Academy_Spec.md) — the ACP protocol suite, v3.2
- [Provenance](Provenance.md) — superseded data kept in `archive/`, and why
- [Flipped-Classroom](Flipped-Classroom.md) — the gamified school program:
  the four-stage flipped loop, grade bands, proposed districts and live units
- [Upgrade-Candidates](Upgrade-Candidates.md) — what the sibling repositories
  offer the Academy, from a reviewed survey

## Honesty

This is a taxonomy of skilled trades, not a roster of chartered locals; no
union has reviewed it. Module counts are addressable module IDs generated
from an authored skeleton, not hand-written lessons. Lesson content is
unverified general practice pending authoring by journey-level practitioners.
{FOOTER}'''


# ------------------------------------------------------------ Campus map ---
def page_campus():
    census = '\n'.join(
        f'| {d["name"]} | {len(d["halls"])} | {F(len(d["halls"]) * L["lessons_per_hall"])} '
        f'| {F(len(d["halls"]) * L["lessons_per_hall"] * L["variants_per_lesson"])} |'
        for d in districts.values())
    graph_edges = '\n'.join(
        f'  campus --> {mermaid_id(k)}["{d["name"]}<br/>{len(d["halls"])} halls"]'
        f'\n  click {mermaid_id(k)} "District-{k}.md"'
        for k, d in districts.items())
    return f'''# The campus map

`web/trade_craft_map.html`, generated by `web/build_map.py` — every one of the
{L["halls"]} union halls on the Treasure Island campus, coloured by district,
with a generated floor plan for each hall (see [Interiors-Map](Interiors-Map.md)).

## What the map encodes

- **Hue carries the district; identity is carried by a unique three-letter
  code** on each hall marker. Colour cannot hold {L["halls"]} categories — the
  hash-a-hue approach produced 94 distinct hues with three-way ties, so the
  encoding changed rather than the tolerance (spec §23.4).
- **Pipeline state** comes from the pack: each hall shows its module census
  across live / calibrating / schema-ok / draft, computed from the same
  position function the registry uses — the map holds no counts of its own.
- **The roster comes from the union registry** (`unions/registry/`); the map
  holds no hall list of its own, so it cannot drift from the taxonomy.

## Content graph

```mermaid
flowchart LR
  campus(("Treasure Island<br/>campus"))
{graph_edges}
```

## Census by district

| District | Halls | Lessons | Core modules |
|---|---|---|---|
{census}

Across the campus: {F(L["core_lessons"])} lessons, {F(L["core_modules"])} core
modules, plus the {F(L["shared_library_modules"])}-module shared cross-trade
library = {F(L["total_modules"])}.

## Rebuilding

```bash
python3 unions/build.py               # if the roster changed
python3 pack/build.py                 # if the skeleton changed
python3 stations/build.py             # if the station content changed
python3 web/build_map.py              # the campus plan
python3 web/build_interactive_map.py  # the interactive layered map
python3 web/build_3d.py               # the 3D hall environment
```

## The interactive layer

`web/trade_craft_interactive.html` (built by `web/build_interactive_map.py`)
puts four toggleable layers over the same registries: district hue, pipeline
state, module layers (each hall's census as a stacked bar), and training
stations. Clicking a hall opens its floor plan with the recovered stations
drawn inside the rooms their strands own, its skill lattice, machine-gradable
scenario checks, and the module registry folded per strand — real generated
lesson rows with their difficulty and pipeline state, from the pack's own
position rule (the JS mirror of that rule is asserted against the pack at
build time in `web/mapdata.py`). The whole surface renders in any of the
shipped locales, direction-aware.

The 3D environment (`web/trade_craft_3d.html`) goes one level deeper. It
opens on the **campus view** — all {L["halls"]} buildings ringed by district
around a central plaza, hue-banded, with beacons on station-seeded halls;
click a building to enter its hall. Inside, rooms are clickable, each
opening its purpose, the trade's own fixtures (also standing in the scene
as benched props), and the same per-strand module rows; safety rooms carry
a hazard-stripe threshold at the doorway, and **walk mode** drops to first
person (WASD, pointer lock) for a floor-level pass through the building.

Each campus carries a typed **roadway network** — a dashed ring road, a
radial spur from the plaza, a street along every building row, a driveway
to every door, and an alley tying the rows back to the ring. Roads and
buildings are laid out in one cluster-local frame with a depth-aware row
pitch, and the build checks itself: any road rectangle overlapping any
building rectangle counts as a fault, and the headless harness asserts
zero across all three campuses. Building rooflines are typed by district
(sawtooth for the industrial districts, gabled for the finish trades,
flat with rooftop plant elsewhere), with corner trims in the district hue.

## Upgrade candidates

Reviewed and held for future releases (see [`ROADMAP.md`](../ROADMAP.md)):

- **Localized chrome** — the map's labels and legend from the i18n catalogs,
  with RTL mirroring (v3.3).
- **Real geography** — the campus plan is a functional layout, not a survey;
  no address data has been collected for any hall, and each floor plan says
  so. A siting pass against real parcels is a v4.0-era decision.
- **Per-hall deep links** — hall markers linking to their wiki district page
  and, once authored, their curriculum.
- **VR walkthrough** — the §24 texture and environment packages make each
  hall's floor plan renderable as a sim environment (v4.0 pilot).
{FOOTER}'''


# --------------------------------------------------------- Interiors map ---
def page_interiors():
    rows = '\n'.join(
        f'| {label} | {w}×{h} | {strand} | {desc} |'
        for strand, label, w, h, desc in ROOMS)
    room_nodes = '\n'.join(
        f'  {strand}["{label}"]' for strand, label, _, _, _ in ROOMS)
    return f'''# The interiors map

Every hall on the campus map opens into a generated floor plan —
{L["halls"]} interiors, {L["halls"] * len(ROOMS):,} rooms — built by
`web/interiors.py` and verified by `web/test_interiors.py` (no room leaves
its envelope, no rooms overlap, every label fits its room at measured
pixel widths — spec §23's rendering lesson).

## The room programme

A hall's rooms mirror the eleven skill strands: the floor the trade is
learned on is the same map as the graph it is sequenced by.

| Room | Grid size | Strand | Purpose |
|---|---|---|---|
{rows}

## Content graph

```mermaid
flowchart TB
  subgraph hall ["One union hall — 12 grid units wide, 3 m per unit"]
{room_nodes}
  end
  safety --> procedure
  procedure --> machines
  procedure --> inspection
  inspection --> documentation
  coordination --> leadership
```

*(Edges show the induction-to-certification flow, not adjacency; the plan
packs rooms per hall by its own focus line and fixtures.)*

## Floor finishes (spec §24, as code)

Every room's floor finish is resolved by `surfaces/build.py` —
**{len(finishes["catalogue"])} finishes** in the catalogue, each carrying
renderer-ready parameters and the reason it exists. Selection runs
most-specific-first: the trade's hazard, then the room's function, and the
record says which rule placed it. {finishes["hazard_placed_finishes"]}
finishes across the network are hazard-placed
({len(finishes["hazards_in_use"])} hazard classes in use); a hazard is
recorded only where it **changed** the outcome, and the
{len(finishes["no_finish_driving_hazard"])} halls whose trade names no
finish-driving hazard say so explicitly rather than leaving a blank. The 3D
environment renders these finishes as the room floors, pattern and all.

## Fixtures and honesty

A fixture is placed only when the hall's own focus line names it — no hall
gets equipment it has no stated use for. Surfaces and room conditions are
**general good practice, not a code reference** — no figure is read from any
jurisdiction's standard, no surface names a product or specification number
(the suite asserts that absence), and each floor plan records that **no
address data has been collected** — the plan is a functional programme, not
a building survey.
{FOOTER}'''


# ------------------------------------------------------------ Skill graph ---
def page_skills():
    n_req = sum(len(s['requires']) for s in skills)
    n_sup = sum(len(s['supports']) for s in skills)
    n_int = sum(len(s['interferes']) for s in skills)
    strands = sorted({s['strand'] for s in skills})
    # A real excerpt: the welders hall's safety/procedure/inspection lattice.
    pick = {s['skill_id']: s for s in skills if s['union'] == 'welders'
            and s['strand'] in ('safety', 'procedure', 'inspection')}
    edges = []
    for s in pick.values():
        for r in s['requires']:
            if r in pick:
                edges.append(f'  {mermaid_id(r.split(".", 1)[1].replace(".", "_"))} '
                             f'--> {mermaid_id(s["skill_id"].split(".", 1)[1].replace(".", "_"))}')
    nodes = '\n'.join(
        f'  {mermaid_id(s["skill_id"].split(".", 1)[1].replace(".", "_"))}'
        f'["{s["strand"]}<br/>{s["tier"]}"]'
        for s in sorted(pick.values(), key=lambda s: s['skill_id']))
    return f'''# The skill graph

`pack/registry/skills.json` — **{F(len(skills))} skills**: every hall carries
the same lattice of {len(strands)} strands × 3 tiers
(fundamentals → applied → mastery), and the sequencer (ACP-15) walks this
graph rather than a fixed syllabus. Curriculum simulation showed the graph
sequencer is the only strategy that certifies anyone, and roughly doubles
durable ability against blocked practice.

## Edge census

| Edge type | Count | Meaning |
|---|---|---|
| `requires` | {F(n_req)} | hard prerequisite — the gate will not open without it |
| `supports` | {F(n_sup)} | transfer — practising one strengthens the other |
| `interferes` | {F(n_int)} | negative transfer — interleaving these thrashes |

## Content graph — one hall's excerpt

The Welding Trades hall's safety / procedure / inspection lattice, drawn
from the registry (tiers gate upward; safety fundamentals gates everything):

```mermaid
flowchart LR
{nodes}
{chr(10).join(sorted(set(edges)))}
```

## The strands

{' · '.join(f'`{s}`' for s in strands)}

Every strand appears in every hall; the room programme of the
[interiors map](Interiors-Map.md) mirrors these same eleven strands.
{FOOTER}'''


# ------------------------------------------------------------- Simulators ---
def page_sims():
    by_campus_name = {k: c['name'] for k, c in campuses.items()}
    blocks = []
    for sid, sm in sims['sims'].items():
        controls = '\n'.join(f'| `{c["keys"]}` | {c["action"]} |'
                             for c in sm['controls'])
        rubric = '\n'.join(f'| {r["axis"]} | {r["measure"]} | `{r["pass"]}` |'
                           for r in sm['rubric'])
        hall_rows = ', '.join(f'**{by_slug[h]["name"]}**' for h in sm['halls'])
        dash = ', '.join(
            f'`{g["label"]}{" " + g["unit"] if g["unit"] else ""}`'
            + (f' (warns at {g["warn_at"]})' if 'warn_at' in g else '')
            for g in sm['dash'])
        blocks.append(f'''## {sm["name"]} ({sm["kind"]})

{sm["task"]}

Trains at: {hall_rows} — each run exercises that hall's
`{sm["skill_strand"]}.{sm["skill_tier"]}` skill.

| Control | Action |
|---|---|
{controls}

| Rubric axis | Measured | Pass |
|---|---|---|
{rubric}

**Cockpit.** A live dash of {len(sm["dash"])} gauges — {dash} — with the
warn thresholds drawn from this registry, not hard-coded in the page.
View modes: {" / ".join(f"`{v}`" for v in sm["view_modes"])}. Audio is a
`{sm["audio"]["engine"]}` engine plus {", ".join(f"`{a}`" for a in sm["audio"]["alerts"])} —
{sm["audio"]["note"]}. Haptic cues ({", ".join(sm["haptics"])}) fire on
gamepad rumble and the vibration API where the platform offers them.

**Pre-shift walkaround.** Five clipboards ring the machine —
{", ".join(f'*{w["point"]}*' for w in sm["walkaround"])} — a habit-builder
the registry declares **not a gate**: nothing locks behind it and marking
it changes no score.

**Regional scenarios.** The campus you train at picks the yard — the
environment varies, the rubric never does:

| Region | Scenario | The yard |
|---|---|---|
{chr(10).join(f'| {by_campus_name[x["campus"]]} | **{x["name"]}** | {x["brief"]} |' for x in sm["scenarios"])}''')
    return f'''# The simulators

{len(sims["sims"])} operable training machines live inside the
[3D environment](Campus-Map.md): open a bound hall and press **▶** (a hall
bound to more than one machine offers the choice). The
physics are schematic — built for practising control discipline (smooth
inputs, swing management, ordered procedure) — and the scoring contract is
the same shape the mentor fabric enforces: **deterministic**. Every rubric
axis is computed from measured state; nothing narrative can change a score.

{chr(10).join(blocks)}

## What a simulator run is not

{sims["honesty"]["status"]}

**And the walkaround:** {sims["honesty"]["walkaround"]}
{FOOTER}'''


# -------------------------------------------------------------- Languages ---
def page_languages():
    rows = '\n'.join(
        f'| `{code}` | {c["language"]} | {c["english_name"]} | {c["dir"]} | {c["translation_status"]} |'
        for code, c in LOCALES.items())
    return f'''# Languages

The Academy ships in **{len(LOCALES)} languages**. The catalogs live in
`i18n/locales/`, the loader in `i18n/catalog.mjs`, and `i18n/test.mjs` holds
every locale to structural parity with the English source and to agreement
with the packs (districts, strands, tiers, bands, modalities, states).

| Code | Language | English name | Direction | Status |
|---|---|---|---|---|
{rows}

The rendered surface is `web/trade_craft_languages.html`
(`python3 web/build_languages.py`) — the overview in every locale,
direction-aware, with figures read from the manifest.

**What is deliberately not translated:** the {L["halls"]} hall names. Trade
names are load-bearing identity and stay in English until reviewed
trade-name translations exist; every locale says so in its own
`honesty.translation` note. Reviewed translations are a
[roadmap](../ROADMAP.md) milestone (v3.3).
{FOOTER}'''


# ------------------------------------------------------------- Provenance ---
def page_provenance():
    return f'''# Provenance — the archive

`archive/` holds superseded working data kept for provenance rather than
deleted. Nothing in it is consumed by any builder or suite, and the figures
lint deliberately skips it: an archived file correctly states the figures of
its own era, which are wrong everywhere else.

| File | What it is | Why it is here |
|---|---|---|
| `archive/map_union_states_33hall.json` | Per-union module-state counts from the 33-hall era (33 entries, 1,089 modules per union, summing to the superseded lesson total) | It was the campus map's data file before the map began computing state from the pack's own position function. Nothing reads it now — a second copy of a truth is a defect even while it agrees (v2.6 defect 12) — but it documents the scale the network grew from. |
| `archive/bac_yard_stations.json` | The 25-station BAC (Bricklayers & Allied Craftworkers) masonry training-yard curriculum — checklists, doctrine, interactive actions, machine-gradable quizzes, yard layout — recovered from the pre-rebrand yard app, where a complete single-file Three.js application sits committed as the repository's README | Genuine orphaned Academy content from before the rebrand, surfaced by the sibling-repository review ([Upgrade-Candidates](Upgrade-Candidates.md)). Its stations map onto the masonry-family halls (`bricklayers`, `masonry-restore`, `stone-carvers`, `tilesetters`, `terrazzo`, `refractory` and more) whose registry slots are currently skeleton-only; folding it in as authored content is roadmap work, so it is preserved here as data first. Pre-rebrand product naming is omitted per `brand/identity.mjs`. |

The 33-hall pack's union indices are preserved verbatim as the first 33
entries of the current roster (`unions/unions111.py`), so every module ID
minted under the old pack still resolves.
{FOOTER}'''


# ---------------------------------------------------------- district pages --
def page_district(key, d):
    members = [by_slug[s] for s in d['halls']]
    rows = []
    for h in members:
        ls = level_states(h['slug'])
        rows.append(
            f'| **{h["name"]}** | {h["focus"]} | {F(h["lessons"])} | {F(h["modules"])} '
            f'| {ls["live"]} / {ls["calibrating"]} / {ls["schema_ok"]} / {ls["draft"]} |')
    nodes = '\n'.join(
        f'  {mermaid_id(key)} --> {mermaid_id(h["slug"])}["{h["name"]}"]'
        for h in members)
    total_modules = sum(h['modules'] for h in members)
    ckey, camp = next((ck, c) for ck, c in campuses.items() if key in c['districts'])
    return f'''# District: {d["name"]}

*{d["tagline"]}* — trains at **{camp["name"]}**, {camp["city"]}, {camp["region"]}.

**{len(members)} halls** · {F(sum(h["lessons"] for h in members))} lessons ·
{F(total_modules)} core modules. Part of the [campus map](Campus-Map.md).

## Content graph

```mermaid
flowchart LR
  {mermaid_id(key)}(("{d["name"]}"))
{nodes}
```

## The halls

Pipeline column counts this hall's 100 levels by state
(live / calibrating / schema-ok / draft).

| Hall | Focus | Lessons | Modules | Levels by state |
|---|---|---|---|---|
{chr(10).join(rows)}

Every hall runs the same skeleton — 100 levels in ten tracks, 110 slots per
level, 9 variants per lesson — sequenced by the
[skill graph](Skill-Graph.md), with an interior generated from the same
strands ([interiors map](Interiors-Map.md)).
{FOOTER}'''


def page_schools():
    stages = '\n'.join(
        f'| **{s["title"]}** | {s["what"]} | `{s["implemented_by"]}` | {s["gamified"]} |'
        for s in schools['model']['stages'])
    bands = '\n'.join(
        f'| {b["band"]} | {b["level"]} | {b["tier"] or "—"} | {b["offer"]} |'
        for b in schools['bands'])
    dists = '\n'.join(
        f'| {d["district"]} | {d["city"]} | {campuses[d["campus"]]["name"]} '
        f'| {d["status"]} |'
        for d in schools['districts'])
    units = '\n'.join(
        f'| **{by_slug[u["hall"]]["name"]}** '
        f'| {", ".join(f"`{s}`" for s in u["floor_sims"])} '
        f'| {len(u["class_stations"]) or "—"} | {u["gate"]} |'
        for u in schools['units'])
    return f'''# The flipped classroom

How the Academy's machinery becomes a school program: **{schools["model"]["loop"]}.**
Every stage below names the subsystem that already implements it, and
`schools/test.mjs` proves those references against the packs that own
them — a program that overclaims fails its build.

| Stage | What happens | Implemented by | The gamified layer |
|---|---|---|---|
{stages}

## Grade bands

Aligned with the Cognition.X band vocabulary (Explorer / Builder /
Practitioner / Lead), so the two platforms' materials sit in one
classroom. Explorer (K–5) is deliberately awareness-only.

| Grades | Band | Academy tier | The offer |
|---|---|---|---|
{bands}

## School districts, honestly

The names below are **public-record identities only** — no address,
enrolment figure or policy is recorded — and every record carries the
same status, asserted by the suite:

| District | City | Nearest campus | Status |
|---|---|---|---|
{dists}

## Flipped units live today

One unit per simulator-bound hall — the halls where the full loop can run
now. The floor stage runs the **regional scenario** of whichever campus
the class trains at ([Simulators](Simulators.md)).

| Hall | Floor sims | Class stations | The gate |
|---|---|---|---|
{units}

## What this is not

{schools["honesty"]["districts"]} {schools["honesty"]["certification"]}
{FOOTER}'''


def page_tools():
    blocks = []
    for dk, crib in tools['cribs'].items():
        rows = '\n'.join(
            f'| {t["glyph"]} **{t["name"]}** | {t["use"]} | `{t["shape"]}` |'
            for t in crib['tools'])
        drill_rows = '\n'.join(
            f'| {i + 1} | {x["ask"]} | `{x["tool"]}` |'
            for i, x in enumerate(tools['drills'][dk]))
        blocks.append(f'''## {crib["name"]} ({districts[dk]["name"]})

| Tool | What it is for | Render shape |
|---|---|---|
{rows}

<details><summary>The {tools["drill"]["name"]} for this crib ({tools["drill"]["picks"]} picks)</summary>

| # | Ask | Answer |
|---|---|---|
{drill_rows}

</details>''')
    n_tools = sum(len(c['tools']) for c in tools['cribs'].values())
    return f'''# The toolrooms

One **tool crib per district** — {len(tools["cribs"])} cribs, {n_tools}
generic hand tools — hung on a pegboard in every hall\'s tools room in the
[3D environment](Campus-Map.md) and listed on every hall panel of the
interactive map. Every hall binds through its district to a real
`tools.applied` skill in the graph, and `tools/test.mjs` proves all
{len(tools["hall_bindings"])} bindings.

**The {tools["drill"]["name"]}.** {tools["drill"]["contract"]}. The suite
re-runs the derivation and requires a byte-identical result.

{chr(10).join(blocks)}

## What a crib is not

{tools["honesty"]["status"]}
{FOOTER}'''


PAGES = {
    'Home.md': page_home,
    'Campus-Map.md': page_campus,
    'Interiors-Map.md': page_interiors,
    'Skill-Graph.md': page_skills,
    'Languages.md': page_languages,
    'Simulators.md': page_sims,
    'Toolrooms.md': page_tools,
    'Flipped-Classroom.md': page_schools,
    'Provenance.md': page_provenance,
    **{f'District-{k}.md': (lambda k=k, d=d: page_district(k, d))
       for k, d in districts.items()},
}


def main():
    check = '--check' in sys.argv
    stale = []
    for name, fn in PAGES.items():
        want = fn()
        path = HERE / name
        if check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.write_text(want)
    if check:
        if stale:
            print('STALE wiki pages: ' + ', '.join(stale))
            print('       run: python3 wiki/build_wiki.py')
            sys.exit(1)
        print(f'wiki is current ({len(PAGES)} pages)')
    else:
        print(f'wiki: {len(PAGES)} pages written')


if __name__ == '__main__':
    main()
