// GENERATED by datashare/build.py from the same object as registry/datashare.json. Do not edit.
export default {
 "intake": {
  "file": "datashare/intake.mjs",
  "endpoint": "/api/datashare/intake",
  "flag_env": "DATASHARE_INTAKE",
  "flag_on_value": "on",
  "flag_default": "off: unless the Worker env sets DATASHARE_INTAKE to \"on\" the route answers 404 like an unknown path",
  "r2_binding": "DATASHARE_R2",
  "key_prefix": "packages/sha256/",
  "key_rule": "content-addressed: packages/sha256/<digest.hex>.json - a second POST of the same package finds the key present and stores nothing new",
  "max_bytes": 1048576,
  "content_type": "application/json",
  "accepts": "tc-contribution/2",
  "accepts_why": "only a /2 package states origin.classroom_mode; a /1 package cannot prove it was not exported in classroom mode, so the intake refuses it by name (the verifier and the dataset builder still accept it)",
  "refuses": [
   "wrong method (405)",
   "flag off (404)",
   "no R2 binding (503)",
   "wrong content-type (415)",
   "oversize (413)",
   "not JSON (400)",
   "record tag not tc-contribution/2 (422)",
   "unconsented: empty or foreign scope, wrong statement or licence (422)",
   "classroom mode (422)",
   "any other verifier rule (422)"
  ],
  "deployed": false,
  "status": "NOT DEPLOYED and OFF by default; tested only against a mocked R2 bucket (datashare/test.mjs)",
  "logs": "nothing: no body, no header, no address"
 },
 "source_stamp": "ebc5ddf1f30546ee"
};
