/* datashare/intake.mjs - POST /api/datashare/intake: accept ONE tc-contribution/2 package, validate it with the
 * contrib verifier core, and store it in R2 under its content address.
 *
 * NOT DEPLOYED and OFF BY DEFAULT. Unless the Worker env sets DATASHARE_INTAKE to exactly "on" this route answers
 * 404 like an unknown path. Tested only against a mocked R2 bucket (datashare/test.mjs); no bucket exists.
 *
 * The validator is the SAME rules `node contrib/verify.mjs` runs: datashare/intake_core.mjs (generated by
 * datashare/build.py) carries contrib/verify.mjs's CONTRIB_CORE block, the sign-in page's AUTH-CORE recovery and
 * the registries verbatim - a Worker cannot read files, so they are carried, and datashare/test.mjs holds the
 * carried bytes to their sources.
 *
 * Refuses, by name: a method other than POST (405), the flag off (404), no R2 binding (503), a content-type other
 * than application/json (415), a body over datashare.json#intake.max_bytes (413), a body that is not JSON (400),
 * a record tag other than tc-contribution/2 (422 - only /2 states origin.classroom_mode), and any verifier failure
 * (422, naming the rule: unconsented scope/statement/licence, classroom mode, privacy, digest, ...).
 * Stores {key: packages/sha256/<digest>.json}; a package already stored is not written again. Nothing is logged.
 */
import { CORE, recoverAddress } from './intake_core.mjs';
import DS from './intake_config.mjs';

const I = DS.intake;
export const INTAKE_ENDPOINT = I.endpoint;
export const INTAKE_CONFIG = I;
const BASE = { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'x-content-type-options': 'nosniff' };

export async function handleIntake(request, env, deps) {
  const headers = { ...BASE };
  for (const h of deps.api_headers) headers[h.key.toLowerCase()] = h.value;
  const reply = (status, body) => new Response(JSON.stringify(body), { status, headers });
  const refuse = (status, code, detail) => reply(status, { ok: false, error: code, detail });
  if (env[I.flag_env] !== I.flag_on_value) return refuse(404, 'not_found', 'no such route');
  if (request.method !== 'POST') return refuse(405, 'method', 'POST only');
  const bucket = env[I.r2_binding];
  if (!bucket || typeof bucket.put !== 'function' || typeof bucket.head !== 'function')
    return refuse(503, 'not_configured', 'datashare: ' + I.r2_binding + ' binding is missing - nothing can be stored');
  const ctype = (request.headers.get('content-type') || '').split(';')[0].trim().toLowerCase();
  if (ctype !== I.content_type) return refuse(415, 'content_type', I.content_type + ' only');
  const len = request.headers.get('content-length');
  if (len !== null && Number(len) > I.max_bytes) return refuse(413, 'too_large', 'package over ' + I.max_bytes + ' bytes');
  const raw = await request.text();
  const bytes = new TextEncoder().encode(raw);
  if (bytes.length > I.max_bytes) return refuse(413, 'too_large', 'package over ' + I.max_bytes + ' bytes');
  let record;
  try { record = JSON.parse(raw); } catch { return refuse(400, 'bad_json', 'body is not JSON'); }
  if (!record || typeof record !== 'object' || Array.isArray(record)) return refuse(400, 'bad_json', 'body is not an object');
  if (record.record !== I.accepts) return refuse(422, 'record', 'only ' + I.accepts + ' is accepted here: ' + I.accepts_why);
  let result;
  try { result = await CORE.verifyAsync(record, deps.subtle, recoverAddress); }
  catch (e) { return refuse(422, 'record.fields', String(e && e.message)); }
  const failed = Object.entries(result.tally).filter(([, t]) => t.fails.length > 0);
  if (failed.length) {
    const [rule, t] = failed[0];
    const code = rule.startsWith('consent.') ? 'unconsented' : (rule === 'origin.classroom' ? 'classroom' : 'invalid');
    return refuse(422, code, rule + ': ' + t.fails[0]);
  }
  const key = I.key_prefix + record.digest.hex + '.json';
  if ((await bucket.head(key)) !== null) return reply(200, { ok: true, key, stored: false, duplicate: true });
  await bucket.put(key, raw, { httpMetadata: { contentType: I.content_type } });
  return reply(200, { ok: true, key, stored: true });
}
