#!/usr/bin/env python3
"""cloudflare/ - how this bundle WOULD be served from Cloudflare. Nothing is deployed.

api.cloudflare.com is blocked from this environment and no Cloudflare account or
token exists, so this pack writes configuration and nothing else. An operator with
an account runs the commands in cloudflare/README.md.

Shape: one Pages project serves the static bundle (the same _site/ that
.github/assemble_site.sh builds for GitHub Pages); one Worker, `smartcitix-payments`
(payments/worker.mjs), answers /api/*. The Pages project reaches the Worker through
a SERVICE BINDING named PAYMENTS from a one-line Pages Function, and _routes.json
limits Functions to /api/*, so every other request is a static file.

Headers are DERIVED, not retyped:
  - every header the committed deploy sets (vercel.json `headers`, the only header
    policy in the tree - security/ publishes none) is copied onto `/*` verbatim;
  - a BASELINE CSP of directives that cannot break a page (no script/style/img
    restriction: the pages carry inline scripts and view-time imagery, so a
    script-src without per-page hashes would break them) - frame-ancestors,
    base-uri, object-src, form-action - AUTHORED here and labelled so;
  - /api/* gets a deny-all CSP (JSON only) and no-store.
No id, account, zone, route pattern with a domain, or secret is written anywhere.
"""
import hashlib
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent


class CloudflareError(Exception):
    pass


def need(d, k, where):
    if k not in d:
        raise CloudflareError(f'cloudflare: {where}.{k} is missing')
    return d[k]


VERCEL = json.loads((ROOT / 'vercel.json').read_text())
CATALOG = json.loads((ROOT / 'payments/registry/catalog.json').read_text())

SITE_HEADERS = []
for rule in need(VERCEL, 'headers', 'vercel.json'):
    if need(rule, 'source', 'vercel.json.headers[]') != '/(.*)':
        raise CloudflareError('cloudflare: vercel.json header rule for a source other than /(.*) - map it by hand, with a test')
    for h in need(rule, 'headers', 'vercel.json.headers[]'):
        SITE_HEADERS.append((need(h, 'key', 'header'), need(h, 'value', 'header')))
if not SITE_HEADERS:
    raise CloudflareError('cloudflare: vercel.json sets no headers to derive from')

BASELINE_CSP = "frame-ancestors 'none'; base-uri 'self'; object-src 'none'; form-action 'self'"
API_CSP = "default-src 'none'; frame-ancestors 'none'"
API_ROUTES = [need(CATALOG['checkout'], 'endpoint', 'checkout'), need(CATALOG['webhook'], 'endpoint', 'webhook')]
KV = need(CATALOG['webhook'], 'kv_binding', 'webhook')
SECRETS = [CATALOG['checkout']['secret_env'], CATALOG['webhook']['secret_env']]
VARS = [CATALOG['checkout']['origin_env']] + [p[k] for p in CATALOG['plans'] for k in ('price_env', 'mode_env')]
COMPAT = '2024-09-23'   # AUTHORED: a compatibility date the operator may move forward

HEADERS = ('# GENERATED by cloudflare/build.py - do not edit. Site headers copied from vercel.json;\n'
           '# the Content-Security-Policy on /* is an AUTHORED baseline (see build.py).\n'
           '/*\n' + ''.join(f'  {k}: {v}\n' for k, v in SITE_HEADERS)
           + f'  Content-Security-Policy: {BASELINE_CSP}\n'
           '/api/*\n'
           f'  Content-Security-Policy: {API_CSP}\n'
           '  Cache-Control: no-store\n')

# vercel.json cleanUrls: /web/x serves web/x.html. Pages already does this; the one
# redirect the bundle needs is the Plans page's short name. Nothing under /api/.
REDIRECTS = ('# GENERATED by cloudflare/build.py - do not edit.\n'
             '/plans /web/trade_craft_plans.html 302\n')

ROUTES = {'version': 1, 'include': ['/api/*'], 'exclude': []}

FUNCTION = ('// GENERATED by cloudflare/build.py - do not edit.\n'
            '// Pages Function for /api/*: hand the request, unchanged, to the payments Worker\n'
            '// through the PAYMENTS service binding. No logic lives here.\n'
            'export const onRequest = ({ request, env }) => {\n'
            '  if (!env.PAYMENTS) return new Response(\'{"ok":false,"error":"not_configured","detail":"PAYMENTS service binding is missing"}\',\n'
            '    { status: 503, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } });\n'
            '  return env.PAYMENTS.fetch(request);\n'
            '};\n')

PAGES_TOML = f'''# GENERATED by cloudflare/build.py - do not edit.
# Cloudflare Pages project for the static bundle. Run from cloudflare/ after
# `bash .github/assemble_site.sh` and `python3 cloudflare/build.py --stage`.
# NOT DEPLOYED: no account, no token; api.cloudflare.com is blocked here.
name = "smartcitix"
pages_build_output_dir = "../_site"
compatibility_date = "{COMPAT}"

# /api/* -> the payments Worker (functions/api/[[path]].js forwards here).
[[services]]
binding = "PAYMENTS"
service = "smartcitix-payments"
'''

WORKER_TOML = f'''# GENERATED by cloudflare/build.py - do not edit.
# The one Worker: payments/worker.mjs. NOT DEPLOYED.
# Secrets (never in this file): {', '.join(SECRETS)} - `wrangler secret put <NAME>`.
# Plain variables (set per deployment, never here): {', '.join(VARS)}.
name = "smartcitix-payments"
main = "../../payments/worker.mjs"
compatibility_date = "{COMPAT}"
workers_dev = false

# The namespace id is account-specific and is NOT committed: create it with
# `wrangler kv namespace create {KV}` and add the printed `id = ...` line in
# your deployment copy of this file.
[[kv_namespaces]]
binding = "{KV}"
'''


def outputs():
    return {
        '_headers': HEADERS,
        '_redirects': REDIRECTS,
        '_routes.json': json.dumps(ROUTES, indent=1) + '\n',
        'functions/api/[[path]].js': FUNCTION,
        'wrangler.toml': PAGES_TOML,
        'worker/wrangler.toml': WORKER_TOML,
        'registry/cloudflare.json': None,
    }


def main():
    import sys
    out = outputs()
    files = {k: v for k, v in out.items() if v is not None}
    for rel, text in files.items():
        p = HERE / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    reg = {
        'pack': 'cloudflare', 'provenance': 'AUTHORED', 'deployed': False,
        'status': 'configuration only - nothing is deployed; no Cloudflare account or token exists here',
        'site_headers_from': 'vercel.json', 'site_headers': [{'key': k, 'value': v} for k, v in SITE_HEADERS],
        'baseline_csp': BASELINE_CSP, 'api_csp': API_CSP, 'api_routes': API_ROUTES,
        'secrets': SECRETS, 'vars': VARS, 'kv_binding': KV, 'service_binding': 'PAYMENTS',
        'files': {k: 'sha256:' + hashlib.sha256(v.encode()).hexdigest() for k, v in sorted(files.items())},
        'source_stamp': 'sha256:' + hashlib.sha256((HERE / 'build.py').read_bytes()).hexdigest(),
    }
    (HERE / 'registry').mkdir(exist_ok=True)
    (HERE / 'registry/cloudflare.json').write_text(json.dumps(reg, indent=1) + '\n')
    if '--stage' in sys.argv:
        site = ROOT / '_site'
        if not site.is_dir():
            raise CloudflareError('cloudflare: _site/ is missing - run .github/assemble_site.sh first')
        for rel in ('_headers', '_redirects', '_routes.json'):
            (site / rel).write_text(files[rel])
        print('cloudflare: staged _headers, _redirects, _routes.json into _site/')
    print(f'cloudflare: {len(files)} files, {len(SITE_HEADERS)} site headers from vercel.json, '
          f'api routes {API_ROUTES}, deployed=False')


if __name__ == '__main__':
    main()
