// GENERATED by cloudflare/build.py - do not edit.
// Pages Function for /api/*: hand the request, unchanged, to the payments Worker
// through the PAYMENTS service binding. No logic lives here.
export const onRequest = ({ request, env }) => {
  if (!env.PAYMENTS) return new Response('{"ok":false,"error":"not_configured","detail":"PAYMENTS service binding is missing"}',
    { status: 503, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } });
  return env.PAYMENTS.fetch(request);
};
