"""Writes sitemap.xml and robots.txt at the bundle root, from web/sitenav.py.

The sitemap lists exactly the pages the site nav lists - PAGES, in its own
order - each at its canonical URL from web/seo.py, so the nav, the canonical
tags and the sitemap cannot describe three different sites. No <lastmod>:
the only honest date would be a commit time this build cannot know, and a
made-up one is worse than none. No <priority> for the same reason.

    python3 web/build_seo.py           # write both
    python3 web/build_seo.py --check   # fail if either is stale
"""
import html
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from staleness import emit  # noqa: E402
from sitenav import PAGES  # noqa: E402
from seo import BASE, canonical  # noqa: E402

ROOT = HERE.parent

for p in PAGES:
    assert (ROOT / p).is_file(), f'build_seo: nav page {p} does not exist'

sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + ''.join(f'  <url><loc>{html.escape(canonical(p))}</loc></url>\n' for p in PAGES)
           + '</urlset>\n')

robots = ('# SmartCiti.X : Trade Craft Academy - generated by web/build_seo.py.\n'
          '# Crawlers read robots.txt only at a host\'s root. On a GitHub Pages\n'
          '# project site this file sits under the repository path, so it is\n'
          '# informative there and takes effect once the site has its own host.\n'
          'User-agent: *\n'
          'Allow: /\n'
          '\n'
          f'Sitemap: {BASE}sitemap.xml\n')

emit(ROOT / 'sitemap.xml', sitemap, f'{len(PAGES)} pages')
emit(ROOT / 'robots.txt', robots, 'allow all, sitemap linked')
